### ISSUE TITLE
Swap PC (WORKPIOF0002) and Mac (WORKPION0001) in Room 411 and ensure 'seamless' digitization possible on Mac

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#124]
- [x] [Make physical swap of computers](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/124#issuecomment-2441873062)
- [x] [Install Canon EOS Utility on Mac](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/124#issuecomment-2441874494)
- [x] [Determine how to get images off of the Mac](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/124#issuecomment-2441876053)

**Comment by chelseagraham** [comment]
### Make physical swap of computers

@Gomismis has made physical swap of computers

**Comment by chelseagraham** [comment]
### Install Canon EOS Utility on Mac

@Gomismis installed Canon EOS Utility on the Mac when she moved the workstations

**Comment by chelseagraham** [comment]
### Determine how to get images off of the Mac

- - [x] **Inquire with Bhupjit about timeline for latest functioning version of Ingestion Client working on Mac** (Chelsea)

@bhsi-snm confirmed with @chelseagraham on Friday 25 October that he believed that he could get the Ingestion Client up and running on Mac in a few weeks, but he would like to explore mapping the Mac to the N:/ first. He will look into if this is possible in week 44.
Bhupjit has a reservation to work on this on 5 November.

- - [x] **Updated timeline for Ingestion Client working for Mac** (Bhupjit)

@bhsi-snm reports on 12 November that the Ingestion Client timeline is not very clear yet. We will therefore form an alternative plan.

- - [x] **Check for connection with N:/ via mapping drive** (Bhupjit)

@bhsi-snm reports on 12 November that he was able to map the N:/ on the Mac

- - [x] **Check for connection with N:/ via webfile** (Chelsea)

@chelseagraham followed the webfile access instructions: 
[Webfile Access.pdf](https://github.com/user-attachments/files/17631091/Webfile.Access.pdf)
and logged in with personal log-in credentials and obtained access to network folders within the webpage.

**It is possible to establish a connection to N:/ via webfile on the Mac at WORKPIOF0002.**

- - [x] **Check for connection with N:/ via VPN** (Chelsea)

@chelseagraham followed the VPN installation and access instructions via https://kunet.ku.dk/employee-guide/Pages/IT/Remote-access.aspx instructions: [VPN - installation .pdf](https://github.com/user-attachments/files/17631037/VPN.-.installation.pdf)
downloaded Cisco AnyConnect, logged into VPN (vpn.ku.dk) with personal log-in credentials, connected to the server (Finder > Go > Connect to Server (smb://unicph.domain/Groupdir/SCI-SNM-DigitalCollections) and obtained access to the network folders directly.

**It is possible to establish a connection to N:/ via VPN on the Mac at WORKPIOF0002.**

- - [x] **Decide best option to get images off of the Mac and create plan/protocol for Ingestion**

The best choice would be to use the Ingestion Client directly on the Mac. Because the timeline is not clear to IT, we cannot rely on this and need to form another plan.
Since it will not be possible to use the ingestion Client within a few weeks, the best current option to get the images off of the Mac to a folder on N:/ would be via mapped drive.

The following protocol should be adopted for ingesting these files remotely from N:/ via Ingestion Client:
Export the previous days images to TIFF in the morning
Move TIFF files to N:/ in the day
Ingest these files from N:/ in the afternoon

**Comment by chelseagraham** [comment]
**Inquire with Bhupjit about timeline for latest functioning version of Ingestion Client working on Mac**

Bhupjit confirmed on Friday 25 October that he believed that he could get the Ingestion Client up and running on Mac in a few weeks

**Comment by bhsi-snm** [comment]
Change in plans, I can do it in week 45, not this week.

**Comment by Gomismis** [comment]
When I swapped out the computers I also installed EOS utility

**Comment by chelseagraham** [comment]
> Change in plans, I can do it in week 45, not this week.

Hey @bhsi-snm I saw that you had a reservation on the Mac yesterday afternoon. How did it go? :)

**Comment by chelseagraham** [comment]
In our development team meeting on 7 November, we agreed that @Gomismis will test out Ingestion via N:/ to see if we can do this without incurring many errors and experiencing slow speeds. This will entail

- creating a folder on N:/ for WORKPIOF0002 acquisitions
- exporting the images taken on the Mac at WORKPIOF0002 to TIFF
- moving the files onto the N:/ via VPN
- running the Ingestion Client remotely from a PC with the destination folder as N:/
- noting any delays and errors

**Comment by chelseagraham** [comment]
> In our development team meeting on 7 November, we agreed that @Gomismis will test out Ingestion via N:/ to see if we can do this without incurring many errors and experiencing slow speeds. This will entail
> 
>     * creating a folder on N:/ for WORKPIOF0002 acquisitions
> 
>     * exporting the images taken on the Mac at WORKPIOF0002 to TIFF
> 
>     * moving the files onto the N:/ via VPN
> 
>     * running the Ingestion Client remotely from a PC with the destination folder as N:/
> 
>     * noting any delays and errors

On 8 November, Matilde carried out the above, running the ingestion client remotely for 38 files (according to the statistics sheet).
She began running the ingestion client at 17:00. The last file has a timestamp of 18:23. 
The 34 TIFF files are timestamped between 17:00 - 17:09. 
The 34 JSON files are all timestamped 18:23.

There are 68 files in the folder (N:/SCI-SNM-DigitalCollections/DaSSCo/MASTER_IMAGE_STORE/Main_image_store/WORKPIOF0002/2024-11-8) although it seems there should be 76, if there were 38 files.

![Screenshot 2024-11-12 at 10 06 28](https://github.com/user-attachments/assets/c67010ee-7dd2-4229-8af2-a9fb9f3bdea9)
![Screenshot 2024-11-12 at 10 06 36](https://github.com/user-attachments/assets/1681586b-4f7c-4e72-a32d-e6cebff64bf5)

FYI @PipBrewer @bhsi-snm

**Comment by bhsi-snm** [comment]
> > Change in plans, I can do it in week 45, not this week.
> 
> Hey @bhsi-snm I saw that you had a reservation on the Mac yesterday afternoon. How did it go? :)

I have mounted n drive on MAC in 411 and it will be automatically mounted every time MAC starts up.
It will be visible on the desktop as a network drive

**Comment by chelseagraham** [comment]
The short term solution is that Digitizers at WORKPIOF0002 will 

- image as usual 
- export images to TIFF as usual 
- transfer images to N:/SCI-SNM-DigitalCollections/DaSSCo/MASTER_IMAGE_STORE/Temporay storage WORKPIOF0002 via the desktop shortcut with the following naming conventions YYMMDD_Initials
- run the Ingestion Client remotely from a PC

The long term solution is that there will be a version of the Ingestion Client that will run on Mac, which @bhsi-snm is working on.
