### ISSUE TITLE
Work on physical set-up

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#127]
- [x] [Research and order necessary elements](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/127#issuecomment-2447213871)
- [x] [Work on base design](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/127#issuecomment-2478483310)
- [x] [Work on sledge design](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/127#issuecomment-2494008871)

**Comment by chelseagraham** [comment]
### Research and order necessary elements

- [x] research and order better ball bearing connections for label cameras 
_[the connection between the KUPO clamp/pin and the camera](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/127#issuecomment-2451550036)_

- [x] determine supports for lateral specimen camera and order 
related ticket: https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/21
@Gomismis has elected some contenders for lateral camera support 
1. [DÖRR Macro Focusing Rail](https://doerr.shop/en-eu/products/doerr-macro-adjustment-slide?variant=48699471200603) 114 DKK
2. [edelkrone FlexTILT Original ](https://edelkrone.com/en-eu/products/flextilt-original?_gl=1*ygdehw*_up*MQ..*_ga*MTcwMTQwODk0LjE3MzE0MDY4OTE.*_ga_QKF11Z581C*MTczMTQwNjg4OC4xLjAuMTczMTQwNjg4OC4wLjAuMA..) $149 ([Goecker](https://goecker.dk/edelkrone-flextilt-head-v3?gad_source=1&gclid=Cj0KCQiAlsy5BhDeARIsABRc6ZtVwzAcy9zEIZepkto-gIJgxujIrxwyTIuSWbc79sE6LyRLaPmk5nYaAr8eEALw_wcB) 870 DKK)
3. [NEEWER Upgraded Z-Flex Tilt Tripod Head](https://eu.neewer.com/products/neewer-upgraded-z-flex-tilt-tripod-head-66600458)  56,99€ 

@chelseagraham ordered 1. DÖRR Macro Focusing Rail on 13 November
[Order #243730 confirmed.pdf](https://github.com/user-attachments/files/17731970/Order.243730.confirmed.pdf)
@chelseagraham ordered 3. NEEWER Upgraded Z-Flex Tilt Tripod Head on 13 November
[Order #NE12718 confirmed.pdf](https://github.com/user-attachments/files/17731699/Order.NE12718.confirmed.pdf)

**Update 11 December** : The NEEWER tripod head was a bust (we received a refund). We will go forward with the edelkrone option.

- [x] decide between Zebra DS2208 2D and Zebra DS9308-SR and order barcode reader
On 29 October, Digitizers (Sara, Jesper, Rebekka) expressed support for trying the Zebra DS9308-SR barcode reader at the ALICE set-up in the NHMDDigiColl daily-dassco-digitisation-queries-and-chat Slack channel.

@chelseagraham ordered Zebra DS9308-SR barcode reader on 13 November
[Bestillingsbekræftelse - ordrenr. 6079140.pdf](https://github.com/user-attachments/files/17732592/Bestillingsbekraeftelse.-.ordrenr.6079140.pdf)

- [x] research and decide if necessary to order lamps and any necessary supports 
related ticket: https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/14
related ticket: https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/12

Options for V1 (MVP) include lamps we already have -Godox LEDP260C LED Panels and Nanlite LumiPad 25 LED Lights which can both be installed on the Kaiser Lamp Arms 5560 via KUPO Clamps and pins, all of which we already have installed on the copystand.
For this v1 MVP ALICE set-up, we will experiment with these and select the best of the two options.
...

**Comment by Gomismis** [comment]
29.10.24: I have ordered 4 heavy duty ballhead, from 'K&F Concept' mounts for our label cameras.

**Comment by Gomismis** [comment]
15.11.2024: I have received the ballhead clamps  
![IMG_8349](https://github.com/user-attachments/assets/a7ee8982-ae71-4507-8dcb-3f6ab77cc556)

**Comment by Gomismis** [comment]
I have also printed the first version of a smaller stage for the ALICE setup. I will use this for measurements when I build the sledge system with Kim next Tuesday. I will try to determine if there are any complications in using a smaller stage and whether it is necessary to have a stage without a rim to avoid disturbing the lateral picture
![IMG_8350](https://github.com/user-attachments/assets/2332d662-a13d-411d-835e-586465d0ca85)

**Comment by chelseagraham** [comment]
### Work on base design

Size considerations:
FOV

Design considerations:
barber brush

3D model history:
1st attempt size:
1st attempt location:
[1st attempt print](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/127#issuecomment-2478466580)

**Comment by Gomismis** [comment]
**Needle for Focus Height:**
Would it be smart to have an extra needle to indicate the height of the specimen to ensure it is in focus? We have discussed using a laser, but we haven’t looked into it yet. Alternatively, there could be a mark on the video feed that we could use for navigation. (see picture below)
![image](https://github.com/user-attachments/assets/23a135fa-2614-4095-8584-1772a06acf3e)

**Camera Mounting:**
The ball head mounts for the label cameras are installed and are both flexible and strong when tightened using a tool to lock them onto the camera and clamp. It is also possible to lock them by hand, but this method is not strong enough to securely hold them in place. (See picture below)
![IMG_8353](https://github.com/user-attachments/assets/75da3c0e-4429-4494-aa18-b3265022a4a3)

I have also moved the two front Kaiser arms (holding two of the label cameras) to the sides of the copy stand (like the two Kaiser arms in the back) to provide more space for accessing the sledge and specimen.  (See picture below)
![IMG_8355](https://github.com/user-attachments/assets/881ca3ea-6954-4d5c-8175-1f63ea6886db)

I replaced the lateral camera (Canon EOS 5D) with one of the label cameras (Canon EOS R5) to measure the distance and space required for this camera/lens combination. The lateral camera will be mounted on either a slide, a Z-flex tilt mount, or both. This should ensure maximum stability and flexibility. As the setup is currently sketched out, the lateral camera would need to be raised 7 cm above the copy stand to achieve a direct lateral view of the specimen.

**Stage and Sledge:**
**The ALICE stage is smaller and will measure 5 cm in height, 12 cm in length, and 9 cm in width.** I think it might be necessary to have a stage without a rim to prevent it from appearing in the pictures, but this requires further investigation. This will depend on the distance between the camera and the specimen. The additional sledge will be 2 cm in height.

The baseplate that everything will be mounted on will be between 1–2 cm thick, depending on Kim’s recommendations for a solid setup that minimizes the risk of shaky pictures. The baseplate will be secured to the copy stand using the already installed Kaiser arms that support the label cameras. (See picture below)
![IMG_8354](https://github.com/user-attachments/assets/06de7a91-71a7-4190-8917-7549fd3350ea)

I hope Kim has a better solution for the sledge rails to prevent the buildup of wax and dust, as we’ve experienced with the simplified setup.

**Infinity Wall:**
I have received gray photo background paper to create the infinity wall behind the specimen. To achieve the appearance of an infinity wall, the paper needs to be attached at approximately the same level as the stage. I am currently working on a simple design to achieve this. (See picture below)
![IMG_8359](https://github.com/user-attachments/assets/1b9f7882-27fd-43b4-9dea-472402b5c827)

**Comment by Gomismis** [comment]
Today Kim and I finished and installed the baseplate/sledge in room 411. 
The base plate includes:

- A brass rail system, hopefully preventing deterioration and build up as the aluminum rail system used on the simplified version. 
- A DÖRR macro focusing rail installed for the lateral camera.
- A infinity wall background stand (still in development)  

The physical set up will most likely be completed by the end of next week (48) and ready for testing. 

To do:
- [x] Receive and install Z flex tilt mount for lateral specimen camera 
- [x] Receive and install 2 x canon R10 label cameras + objectives 
- [x] Laser cut and install gray card to fit stage (Tuesday, November 26) 
- [x] Install photo paper background for infinity wall 
- [ ] Decide on lamps (possibly Nanlink lamps from Århus Herbarium)

**Comment by Gomismis** [comment]
**Label Cameras**
![Image](https://github.com/user-attachments/assets/207e5f97-aefa-468b-b631-920392446dcc)
The label cameras are mounted to the Kaiser arms, which also secure Kim’s base plate. The ball head mounts support the cameras but need to be tightened using small allen key holes (described in this GitHub ticket). However, this may not be sustainable in the long-term, as frequent camera adjustments could cause the mounts to loosen. Once we finalize the camera angle, I suggest designing and 3D-printing a tilted mount to attach to the base plate. This will allow us to install a macro focus rail for more stable, adjustable positioning.

**Lateral Camera**
![Image](https://github.com/user-attachments/assets/4ae5c9e7-644a-4311-8954-34cbc730b573)
The lateral camera setup uses a DÖRR macro focus mount for horizontal adjustments and a Neewer Z-Flex Tilt mount. However, the Neewer mount can’t hold the setup (total weight: 1508 g), even though it’s rated for 3 kg. I’ve submitted a complaint to the manufacturer. Meanwhile, Goecker lent us a similar product that works well ([link](https://bit.ly/3QehZGR)), with Allen key-secured joints and side-to-side rotation. It’s effective but expensive. Let me know if you think it's overkill; we can return it to Goecker if needed. 

**Lenses**
The focus point for labels is very small, and I haven’t been able to get a clear focus on a full label, especially two. We need to investigate this further.

**Baseplate**
Kim built us a baseplate with a sledge function, embedding the DÖRR mount into it. However, Kim measured the baseplate height incorrectly, requiring milling along the edge for the Kaiser arms to fit. As a result, the DÖRR mount slightly hangs off the milled edge. Kim believes it’s not an issue, but we should assess how it works and let him know if any corrections are needed. 

**Sledge System**
![Image](https://github.com/user-attachments/assets/3c9449d0-5972-4376-a324-6124a5c1f8b7)
The stage is about a quarter of the size of the simplified version’s sledge, so the sledge and rail distance are smaller. The rails are made from brass to prevent residue buildup. Anders suggested adding a brass trim around the sledge edge, but I think it could hinder further development.

**Infinity Wall**
![Image](https://github.com/user-attachments/assets/f45e947b-55e5-4af2-aa5c-39d9708ae0d4)
I experimented with an infinity wall by placing a small wooden block behind the stage, slightly lower than the stage to remain out of view. I initially used gray photo background paper, adhering one end to create the infinity effect, but the piece wasn’t wide enough for the full frame. I glued the paper to foam and placed it between the rail and the block for further testing. Feel free to experiment with what works best.
I’ve placed the paper on your desk but note that the background paper has two different shades of gray, neither matching the gray card on the stage.

**Stage**
![Image](https://github.com/user-attachments/assets/24872da5-a67c-4dd7-ae90-dd74aa0ef84e)
The stage is now smaller, with the following updates:
1.	Taller legs lift the brush holder off the ground, so the sledge center doesn’t need to be milled down.
2.	The stage is secured with a LEGO-inspired system rather than magnets.
3.	The gray card is secured with double-sided adhesive tape instead of a rim, as it would show in the lateral view.

**Lighting**
I haven’t tested the lights yet, but I’ve installed two Kaiser arms holding two GODOX LEDP260C light panels. We also have extra light panels from Århus’ herbarium setup to experiment with.
Note that the cameras could cast a shadow if the light is behind them, so lowering the cameras or adding a ring light might help.

**Connection**
![Image](https://github.com/user-attachments/assets/3615ca80-7c3d-4f30-a6ca-990c168db4b7)
I’ve experienced tethering issues, but not with DigiCamControl. It’s a physical connection problem, and we need a solution to secure the connection. As a temporary fix, I’ve attached the USB docks to the PC tower with double-sided adhesive tape to prevent them from hanging.

**Workstation Setup**
I’ve streamlined the workstation to create more space and improve workflow, but a few elements are still missing for it to be fully functional. Here are my suggestions:

- A table with an under-table compartment for the PC tower. The table needs to be at least 70 cm deep (same as the copy stand) to face the digitizer, reducing twisting and straining movements while digitizing.
- An extra screen and a dual flexible monitor arm. DigiCamControl has the option to show all the cameras on live view. To get the most out of this function, it would be beneficial to have one screen dedicated solely to live view.
- A smaller worktable for specimens. I suggest it be on wheels with locks for easy maneuverability.

**Comment by Gomismis** [comment]
Most important development points from now: 

- General adjustment and positioning of all cameras  
- Testing out the Z-tilt mount for the lateral camera 
- Test out background color/infinity wall
- Test out light solution

**Comment by chelseagraham** [comment]
18 December

### Adjusted Camera positions and settings

**DORSAL R5 (#0042)**
- lowered the camera on the copy stand to the established 281 mm focal distance (297 mm on the Kaiser copy stand column)
- adjusted or ensured camera settings of M, ISO 100, 0.4 s, F14
- _could possibly be re-centered - check when testing a range of specimens_

**LATERAL R5 (#0041)**
- moved in on the rail to the established 281 mm focal distance (0 on the DÖRR macro focusing rail)
- adjusted or ensured camera settings of M, ISO 100, 0.4 s, F14
- _could possibly be raised or lowered - check when testing a range of specimens_
- _should be leveled once altered_

**FRONT LEFT R10 (#0484)**
- moved camera to established 450 mm focal distance (6 on the Kaiser light arm and adjusted angle on K&F Concept mount)
- adjusted or ensured camera settings of M, ISO 100, 0.4 s, F14 (needed to manually change shutter speed on camera back)
- _could possibly alter position, but need to maintain a 450 - 500 mm focal distance - check when testing a range of specimens_

**FRONT RIGHT R10 (#0477)**
- moved camera to established 450 mm focal distance (6 on the Kaiser light arm and adjusted angle on K&F Concept mount)
- adjusted or ensured camera settings of M, ISO 100, 0.4 s, F14 (needed to manually change shutter speed on camera back)
- _could possibly alter position, but need to maintain a 450 - 500 mm focal distance - check when testing a range of specimens_

**BACK RIGHT R10 (#0479)**
- moved camera to established 450 mm focal distance (6 on the Kaiser light arm and adjusted angle on K&F Concept mount)
- adjusted or ensured camera settings of M, ISO 100, 0.4 s, F14 (needed to manually change shutter speed on camera back)
- _could possibly alter position, but need to maintain a 450 - 500 mm focal distance - check when testing a range of specimens_

**BACK LEFT R10 (#0487)**
- moved camera to established 450 mm focal distance (6 on the Kaiser light arm and adjusted angle on K&F Concept mount)
- adjusted or ensured camera settings of M, ISO 100, 0.4 s, F14 (needed to manually change shutter speed on camera back)
- _could possibly alter position, but need to maintain a 450 - 500 mm focal distance - check when testing a range of specimens_


### Impressions

- It isn't possible to adjust the shutter speed of R10 cameras in digiCamControl under M selection. This had to be done on the back of each camera.
- The USB docks need a stronger mounting solution. The tape holding them to the PC has come unstuck.
- As stated [above](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/127#issuecomment-2447213871), we should experiment with the two light options that we have in house (Godox LED 260C LED Panels that have been installed on the set-up for some time and the Lumipad 25 LED panels that we used to use in WORKHERB0001 and WORKHERB0002) for this v1 MVP of ALICE, but could consider a smaller panel for a next version, like the [LUPO Kickasspanel Full Color](https://goecker.dk/detalje/lys/led-lys/lupolight-kickasspanel-full-color-1) 
- The infinity wall works well for the lateral image! There are some gaps in the label images, but I don't think it will negatively impact the image or impair OCR, etc. of the label contents. We should get the same material as the base board set up for imaging, so the color is the same (although the lighting will impact this slightly). For a next version, we could consider making a built in infinity wall on the stage from the base plate extending up.
- I couldn't access the lego-esque system and didn't want to force anything and Hulk-out and end up breaking something.

### Suggested Refinements / Testing
(some rehashed)
- To purchase: sturdier ball mounts for the cameras than [these ](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/127#issuecomment-2451550036)
- Refinements of camera positions (possibly adjust depth of dorsal camera and height of lateral camera slightly
- Lighting (see just above) to test
- Infinity wall (see just above)
- Stage depth for multiple labels
- Table from Herbarium C with an under desk compartment for the PC and keyboard drawer arriving in January
- To purchase: additional screen
- To purchase: extra screen
- To purchase: arm for screen placement
- To purchase: worktable base don thoughts of Digitizers on those at WORKPIOF0001 and WORKPIOF0002

**Comment by chelseagraham** [comment]
Unresolved issues transferred over to refinements ticket https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/145
